<?php 
$currentPage = 'about';
// isikeliame visa headeri
// require();
require './inc/header.php';
// include './inc/header.php';
?>

<section class="about-us container" style="margin-top: 100px;">
    <h2>This is about us page</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus explicabo quo nostrum quia rem odio recusandae aspernatur magnam tempora sint animi possimus cum nobis, repellendus beatae aperiam, officia adipisci esse cumque consectetur. Quos veniam ex enim? Quisquam dicta doloremque earum eveniet vitae quam reiciendis corporis iusto fuga. Nihil et consectetur itaque doloremque, temporibus facilis porro totam magni deserunt vero fugiat id, in modi rerum accusamus quasi autem minima! Autem voluptates aperiam sint voluptas vero esse nisi et beatae optio ut sequi quos molestiae odit ipsa at, consequuntur nemo quasi accusantium magnam? Laborum mollitia in sint eaque rerum cum, nisi possimus hic impedit vitae voluptatem officia, totam esse nemo fugiat eveniet itaque aliquid vero adipisci minus! Culpa aspernatur, eos tempore saepe officiis totam velit illo quisquam temporibus, quis reiciendis eligendi est modi rerum consequuntur aut iure aperiam impedit minima rem? Totam reiciendis laudantium quas in necessitatibus non illum ipsa sapiente? Quae optio hic asperiores nihil voluptas libero voluptatum et ut fugit aliquid laudantium fuga atque iusto voluptatibus, debitis ad voluptates reiciendis vitae consequatur eligendi explicabo quibusdam veritatis porro dolores? Iusto exercitationem molestias rem, facilis mollitia aliquam numquam, optio atque illo dicta necessitatibus nisi. Nulla quos aspernatur, distinctio rem soluta numquam eaque magni ipsam ipsa nostrum quas laborum maxime, officia fuga esse iste natus inventore dolorem nihil nam vero earum cum at? Numquam recusandae, nihil nesciunt delectus ex expedita atque deserunt dolorum unde excepturi ea optio aliquam culpa ab modi temporibus! Consequuntur tempora rem eveniet, voluptatum libero, cupiditate nesciunt natus nisi dolorem illum, vel ad hic perferendis similique quibusdam molestiae aliquid voluptatem a ex amet quisquam ab rerum facere! Quasi perferendis saepe delectus ipsa et incidunt, necessitatibus laboriosam dicta consequuntur itaque vitae distinctio nesciunt numquam cupiditate reiciendis sunt earum? Adipisci id quam suscipit sed quis velit neque unde, eos beatae aliquam nobis ullam optio nemo doloremque nisi nulla quae consequuntur! Assumenda laborum deserunt consequuntur ipsam dolorem qui cumque ut animi dicta labore facere adipisci quae similique tempora totam saepe excepturi, perspiciatis quisquam soluta modi! Quae natus quia veniam doloremque debitis minima illo, aliquam quos totam dignissimos eius velit atque facilis nesciunt pariatur sint est, iste dolore. Reprehenderit voluptatum quia dignissimos quisquam, quam perspiciatis, omnis asperiores saepe itaque officia at sit! Assumenda, deserunt placeat! Molestias, blanditiis officia dolorem dolore architecto vel accusantium voluptate deserunt dolor voluptatem nobis temporibus recusandae vero provident consequuntur! Consequatur aut optio ex eius. Nulla consequatur omnis labore minus itaque?</p>
</section>


<?php require './inc/footer.php';